services:
  - docker

stages:
  - name: build docker image
    if: branch != master || type != push
  - name: deploy docker image
    if: (branch = master || tag IS present) && type = push

jobs:
  include:
    - stage: build docker image
      script: docker build -t $DOCKER_IMAGE_NAME .

    - stage: deploy docker image
      script:
        - docker build -t $DOCKER_IMAGE_NAME .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_IMAGE_NAME
        - |
          if [ ! -z "$TRAVIS_TAG" ]; then
            docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:$TRAVIS_TAG
            docker push $DOCKER_IMAGE_NAME:$TRAVIS_TAG
          fi
